name: Run Selenium

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run_selenium:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox]
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
         command: install -d
      - name: Run Selenium tests on ${{matrix.browser}}
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
         command: run pytest --reruns 1 -k ${{matrix.browser}} -vv
      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-report-${{matrix.browser}}
          path: ./allure-results
  upload_github_pages: 
      needs:
       - run_selenium
      if: always() 
      runs-on: ubuntu-latest
      steps: 
        - uses: actions/download-artifact@v3
          with:
            name: 'allure-report-chrome'
            path: allure-results
        - uses: actions/download-artifact@v3
          with:
            name: 'allure-report-firefox'
            path: allure-results    
        - name: Display structure of downloaded files
          run: ls -R
        - name: Allure results
          uses: simple-elf/allure-report-action@master
          id: allure-report
          with:
            allure_results: allure-results
            allure_report: allure-report
            gh_pages: gh-pages
            allure_history: allure-history
        - name: Deploy report to Github Pages
          if: always()
          uses: peaceiris/actions-gh-pages@v3
          with:
            PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            PUBLISH_BRANCH: gh-pages
            PUBLISH_DIR: allure-history
  
