name: Run Selenium

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run_selenium:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Python Dependency Installation
        uses: py-actions/py-dependency-install@v4.0.0
      - name: Install plugin
        run: pip install pytest-github-actions-annotate-failures
      - name: Run Selenium tests on ${{matrix.browser}}
        run: |
          pipenv pytest --reruns 1 -k ${{matrix.browser}} -vv
      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-report-${{matrix.browser}}
          path: ./allure-results
  upload_github_pages: 
      needs:
       - run_selenium
      if: always() 
      runs-on: ubuntu-latest
      steps: 
        - uses: actions/download-artifact@v3
          with:
            name: 'allure-report-chrome'
            path: allure-results
        - uses: actions/download-artifact@v3
          with:
            name: 'allure-report-firefox'
            path: allure-results    
        - name: Display structure of downloaded files
          run: ls -R
        - name: Allure results
          uses: simple-elf/allure-report-action@master
          id: allure-report
          with:
            allure_results: allure-results
            allure_report: allure-report
            gh_pages: gh-pages
            allure_history: allure-history
        - name: Deploy report to Github Pages
          if: always()
          uses: peaceiris/actions-gh-pages@v3
          with:
            PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            PUBLISH_BRANCH: gh-pages
            PUBLISH_DIR: allure-history
  
