name: Run Selenium

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run_selenium:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev
      - name: Run Selenium tests on ${{matrix.browser}}
        run: pipenv run pytest --reruns 1 -k ${{matrix.browser}} -vv
      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-report-${{matrix.browser}}
          path: ./allure-results
  upload_github_pages: 
      needs:
       - run_selenium
      if: always() 
      runs-on: ubuntu-latest
      steps: 
        - uses: actions/download-artifact@v3
          with:
            name: 'allure-report-chrome'
            path: allure-results
        - uses: actions/download-artifact@v3
          with:
            name: 'allure-report-firefox'
            path: allure-results    
        - name: Display structure of downloaded files
          run: ls -R
        - name: Allure results
          uses: simple-elf/allure-report-action@master
          id: allure-report
          with:
            allure_results: allure-results
            allure_report: allure-report
            gh_pages: gh-pages
            allure_history: allure-history
        - name: Deploy report to Github Pages
          if: always()
          uses: peaceiris/actions-gh-pages@v3
          with:
            PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            PUBLISH_BRANCH: gh-pages
            PUBLISH_DIR: allure-history
  
